-- MySQL Script generated by MySQL Workbench
-- Wed Jul  5 10:47:14 2017
-- Model: New Model    Version: 1.0
-- MySQL Workbench Forward Engineering

SET @OLD_UNIQUE_CHECKS=@@UNIQUE_CHECKS, UNIQUE_CHECKS=0;
SET @OLD_FOREIGN_KEY_CHECKS=@@FOREIGN_KEY_CHECKS, FOREIGN_KEY_CHECKS=0;
SET @OLD_SQL_MODE=@@SQL_MODE, SQL_MODE='TRADITIONAL,ALLOW_INVALID_DATES';

-- -----------------------------------------------------
-- Schema sid_database
-- -----------------------------------------------------
DROP SCHEMA IF EXISTS `sid_database` ;

-- -----------------------------------------------------
-- Schema sid_database
-- -----------------------------------------------------
CREATE SCHEMA IF NOT EXISTS `sid_database` DEFAULT CHARACTER SET utf8 ;
USE `sid_database` ;

-- -----------------------------------------------------
-- Table `sid_database`.`Departamento`
-- -----------------------------------------------------
DROP TABLE IF EXISTS `sid_database`.`Departamento` ;

CREATE TABLE IF NOT EXISTS `sid_database`.`Departamento` (
  `id_departamento` INT NOT NULL AUTO_INCREMENT,
  `titulo` CHAR(100) NULL,
  `local` CHAR(45) NULL,
  `telefone` CHAR(45) NULL,
  `email` CHAR(100) NULL,
  `pagina_web` CHAR(100) NULL,
  PRIMARY KEY (`id_departamento`))
ENGINE = InnoDB;


-- -----------------------------------------------------
-- Table `sid_database`.`Curso_Graduacao`
-- -----------------------------------------------------
DROP TABLE IF EXISTS `sid_database`.`Curso_Graduacao` ;

CREATE TABLE IF NOT EXISTS `sid_database`.`Curso_Graduacao` (
  `id_curso_graduacao` INT NOT NULL AUTO_INCREMENT,
  `titulo` CHAR(45) NULL,
  `num_total_periodo` INT(11) NULL,
  `pagina_web` CHAR(100) NULL,
  `id_departamento` INT(11) NOT NULL,
  PRIMARY KEY (`id_curso_graduacao`),
  INDEX `fk_Curso_Graduacao_Departamento1_idx` (`id_departamento` ASC),
  CONSTRAINT `fk_Curso_Graduacao_Departamento1`
    FOREIGN KEY (`id_departamento`)
    REFERENCES `sid_database`.`Departamento` (`id_departamento`)
    ON DELETE NO ACTION
    ON UPDATE NO ACTION)
ENGINE = InnoDB;


-- -----------------------------------------------------
-- Table `sid_database`.`Aluno`
-- -----------------------------------------------------
DROP TABLE IF EXISTS `sid_database`.`Aluno` ;

CREATE TABLE IF NOT EXISTS `sid_database`.`Aluno` (
  `id_aluno` INT NOT NULL AUTO_INCREMENT,
  `dre` CHAR(16) NULL,
  `nome` CHAR(100) NULL,
  `data_nascimento` DATE NULL,
  `sexo` TINYINT(1) NULL,
  `id_curso_graduacao` INT NOT NULL,
  PRIMARY KEY (`id_aluno`),
  UNIQUE INDEX `cd_dre_UNIQUE` (`dre` ASC),
  INDEX `fk_Aluno_Curso_Graduacao1_idx` (`id_curso_graduacao` ASC),
  CONSTRAINT `fk_Aluno_Curso_Graduacao1`
    FOREIGN KEY (`id_curso_graduacao`)
    REFERENCES `sid_database`.`Curso_Graduacao` (`id_curso_graduacao`)
    ON DELETE NO ACTION
    ON UPDATE NO ACTION)
ENGINE = InnoDB;


-- -----------------------------------------------------
-- Table `sid_database`.`Professor`
-- -----------------------------------------------------
DROP TABLE IF EXISTS `sid_database`.`Professor` ;

CREATE TABLE IF NOT EXISTS `sid_database`.`Professor` (
  `id_professor` INT NOT NULL AUTO_INCREMENT,
  `cd_siape` CHAR(45) NULL,
  `nome` CHAR(45) NULL,
  `data_nascimento` CHAR(45) NULL,
  `sexo` TINYINT(1) NULL,
  `id_departamento` INT NOT NULL,
  PRIMARY KEY (`id_professor`),
  INDEX `fk_Professor_Departamento_idx` (`id_departamento` ASC),
  CONSTRAINT `fk_Professor_Departamento`
    FOREIGN KEY (`id_departamento`)
    REFERENCES `sid_database`.`Departamento` (`id_departamento`)
    ON DELETE NO ACTION
    ON UPDATE NO ACTION)
ENGINE = InnoDB;


-- -----------------------------------------------------
-- Table `sid_database`.`Disciplina`
-- -----------------------------------------------------
DROP TABLE IF EXISTS `sid_database`.`Disciplina` ;

CREATE TABLE IF NOT EXISTS `sid_database`.`Disciplina` (
  `id_disciplina` INT NOT NULL AUTO_INCREMENT,
  `codigo` CHAR(16) NULL,
  `titulo` CHAR(45) NULL,
  `ementa` CHAR(45) NULL,
  `num_creditos` INT(11) NULL,
  `carga_horaria` INT(11) NULL,
  `id_departamento` INT NOT NULL,
  PRIMARY KEY (`id_disciplina`),
  INDEX `fk_Disciplina_Departamento1_idx` (`id_departamento` ASC),
  CONSTRAINT `fk_Disciplina_Departamento1`
    FOREIGN KEY (`id_departamento`)
    REFERENCES `sid_database`.`Departamento` (`id_departamento`)
    ON DELETE NO ACTION
    ON UPDATE NO ACTION)
ENGINE = InnoDB;


-- -----------------------------------------------------
-- Table `sid_database`.`Turma`
-- -----------------------------------------------------
DROP TABLE IF EXISTS `sid_database`.`Turma` ;

CREATE TABLE IF NOT EXISTS `sid_database`.`Turma` (
  `id_turma` INT NOT NULL AUTO_INCREMENT,
  `ano` INT(11) NULL,
  `semestre` INT(11) NULL,
  `sala` CHAR(45) NULL,
  `horario_inicio` INT(11) NULL,
  `horario_fim` INT(11) NULL,
  `vagas_totais` INT(11) NOT NULL,
  `id_professor` INT NOT NULL,
  `id_disciplina` INT NOT NULL,
  PRIMARY KEY (`id_turma`),
  INDEX `fk_Turma_Professor1_idx` (`id_professor` ASC),
  INDEX `fk_Turma_Disciplina1_idx` (`id_disciplina` ASC),
  CONSTRAINT `fk_Turma_Professor1`
    FOREIGN KEY (`id_professor`)
    REFERENCES `sid_database`.`Professor` (`id_professor`)
    ON DELETE NO ACTION
    ON UPDATE NO ACTION,
  CONSTRAINT `fk_Turma_Disciplina1`
    FOREIGN KEY (`id_disciplina`)
    REFERENCES `sid_database`.`Disciplina` (`id_disciplina`)
    ON DELETE NO ACTION
    ON UPDATE NO ACTION)
ENGINE = InnoDB;


-- -----------------------------------------------------
-- Table `sid_database`.`Inscricao`
-- -----------------------------------------------------
DROP TABLE IF EXISTS `sid_database`.`Inscricao` ;

CREATE TABLE IF NOT EXISTS `sid_database`.`Inscricao` (
  `id_aluno` INT NOT NULL,
  `id_turma` INT NOT NULL,
  `nota` REAL NULL,
  INDEX `fk_Inscricao_Aluno1_idx` (`id_aluno` ASC),
  INDEX `fk_Inscricao_Turma1_idx` (`id_turma` ASC),
  CONSTRAINT `fk_Inscricao_Aluno1`
    FOREIGN KEY (`id_aluno`)
    REFERENCES `sid_database`.`Aluno` (`id_aluno`)
    ON DELETE NO ACTION
    ON UPDATE NO ACTION,
  CONSTRAINT `fk_Inscricao_Turma1`
    FOREIGN KEY (`id_turma`)
    REFERENCES `sid_database`.`Turma` (`id_turma`)
    ON DELETE NO ACTION
    ON UPDATE NO ACTION)
ENGINE = InnoDB;


-- -----------------------------------------------------
-- Table `sid_database`.`Grade`
-- -----------------------------------------------------
DROP TABLE IF EXISTS `sid_database`.`Grade` ;

CREATE TABLE IF NOT EXISTS `sid_database`.`Grade` (
  `id_curso_graduacao` INT NOT NULL,
  `periodo` INT NULL,
  `id_disciplina` INT NOT NULL,
  INDEX `fk_Grade_Curso_Graduacao1_idx` (`id_curso_graduacao` ASC),
  INDEX `fk_Grade_Disciplina1_idx` (`id_disciplina` ASC),
  CONSTRAINT `fk_Grade_Curso_Graduacao1`
    FOREIGN KEY (`id_curso_graduacao`)
    REFERENCES `sid_database`.`Curso_Graduacao` (`id_curso_graduacao`)
    ON DELETE NO ACTION
    ON UPDATE NO ACTION,
  CONSTRAINT `fk_Grade_Disciplina1`
    FOREIGN KEY (`id_disciplina`)
    REFERENCES `sid_database`.`Disciplina` (`id_disciplina`)
    ON DELETE NO ACTION
    ON UPDATE NO ACTION)
ENGINE = InnoDB;


-- -----------------------------------------------------
-- Table `sid_database`.`Coordena`
-- -----------------------------------------------------
DROP TABLE IF EXISTS `sid_database`.`Coordena` ;

CREATE TABLE IF NOT EXISTS `sid_database`.`Coordena` (
  `id_professor` INT NOT NULL,
  `id_curso_graduacao` INT NOT NULL,
  INDEX `fk_Coordena_Professor1_idx` (`id_professor` ASC),
  INDEX `fk_Coordena_Curso_Graduacao1_idx` (`id_curso_graduacao` ASC),
  CONSTRAINT `fk_Coordena_Professor1`
    FOREIGN KEY (`id_professor`)
    REFERENCES `sid_database`.`Professor` (`id_professor`)
    ON DELETE NO ACTION
    ON UPDATE NO ACTION,
  CONSTRAINT `fk_Coordena_Curso_Graduacao1`
    FOREIGN KEY (`id_curso_graduacao`)
    REFERENCES `sid_database`.`Curso_Graduacao` (`id_curso_graduacao`)
    ON DELETE NO ACTION
    ON UPDATE NO ACTION)
ENGINE = InnoDB;


-- -----------------------------------------------------
-- Table `sid_database`.`Chefia`
-- -----------------------------------------------------
DROP TABLE IF EXISTS `sid_database`.`Chefia` ;

CREATE TABLE IF NOT EXISTS `sid_database`.`Chefia` (
  `id_professor` INT NOT NULL,
  `id_departamento` INT NOT NULL,
  INDEX `fk_Chefia_Professor1_idx` (`id_professor` ASC),
  INDEX `fk_Chefia_Departamento1_idx` (`id_departamento` ASC),
  CONSTRAINT `fk_Chefia_Professor1`
    FOREIGN KEY (`id_professor`)
    REFERENCES `sid_database`.`Professor` (`id_professor`)
    ON DELETE NO ACTION
    ON UPDATE NO ACTION,
  CONSTRAINT `fk_Chefia_Departamento1`
    FOREIGN KEY (`id_departamento`)
    REFERENCES `sid_database`.`Departamento` (`id_departamento`)
    ON DELETE NO ACTION
    ON UPDATE NO ACTION)
ENGINE = InnoDB;


-- -----------------------------------------------------
-- Table `sid_database`.`Requisitos`
-- -----------------------------------------------------
DROP TABLE IF EXISTS `sid_database`.`Requisitos` ;

CREATE TABLE IF NOT EXISTS `sid_database`.`Requisitos` (
  `id_disciplina` INT NOT NULL,
  `id_requisito` INT NOT NULL,
  INDEX `fk_Requisitos_Disciplina1_idx` (`id_disciplina` ASC),
  INDEX `fk_Requisitos_Disciplina2_idx` (`id_requisito` ASC),
  CONSTRAINT `fk_Requisitos_Disciplina1`
    FOREIGN KEY (`id_disciplina`)
    REFERENCES `sid_database`.`Disciplina` (`id_disciplina`)
    ON DELETE NO ACTION
    ON UPDATE NO ACTION,
  CONSTRAINT `fk_Requisitos_Disciplina2`
    FOREIGN KEY (`id_requisito`)
    REFERENCES `sid_database`.`Disciplina` (`id_disciplina`)
    ON DELETE NO ACTION
    ON UPDATE NO ACTION)
ENGINE = InnoDB;


-- -----------------------------------------------------
-- Table `sid_database`.`Dias Semana`
-- -----------------------------------------------------
DROP TABLE IF EXISTS `sid_database`.`Dias Semana` ;

CREATE TABLE IF NOT EXISTS `sid_database`.`Dias Semana` (
  `idDias Semana` INT NOT NULL,
  PRIMARY KEY (`idDias Semana`))
ENGINE = InnoDB;


-- -----------------------------------------------------
-- Table `sid_database`.`Turma_has_Dias Semana`
-- -----------------------------------------------------
DROP TABLE IF EXISTS `sid_database`.`Turma_has_Dias Semana` ;

CREATE TABLE IF NOT EXISTS `sid_database`.`Turma_has_Dias Semana` (
  `Turma_id_turma` INT NOT NULL,
  `Dias Semana_idDias Semana` INT NOT NULL,
  PRIMARY KEY (`Turma_id_turma`, `Dias Semana_idDias Semana`),
  INDEX `fk_Turma_has_Dias Semana_Dias Semana1_idx` (`Dias Semana_idDias Semana` ASC),
  INDEX `fk_Turma_has_Dias Semana_Turma1_idx` (`Turma_id_turma` ASC),
  CONSTRAINT `fk_Turma_has_Dias Semana_Turma1`
    FOREIGN KEY (`Turma_id_turma`)
    REFERENCES `sid_database`.`Turma` (`id_turma`)
    ON DELETE NO ACTION
    ON UPDATE NO ACTION,
  CONSTRAINT `fk_Turma_has_Dias Semana_Dias Semana1`
    FOREIGN KEY (`Dias Semana_idDias Semana`)
    REFERENCES `sid_database`.`Dias Semana` (`idDias Semana`)
    ON DELETE NO ACTION
    ON UPDATE NO ACTION)
ENGINE = InnoDB;


SET SQL_MODE=@OLD_SQL_MODE;
SET FOREIGN_KEY_CHECKS=@OLD_FOREIGN_KEY_CHECKS;
SET UNIQUE_CHECKS=@OLD_UNIQUE_CHECKS;
